version: 1.0
build:
  os: ubuntu-20.04
  tools:
    # python: "miniconda3-4.7"
    python: 3.8

# Optionally set the version of Python and requirements required to build your docs
python: 
  version: 3.8
  install:
    - method: pip
 
     
conda:
  environment: maintainer/conda/environment.yml
