version: 1.0


# Set the build environment to Ubuntu 20.04
# (this is the default build environment on ReadTheDocs)
image: latest

build:
  # Install Conda packages
  - conda install --yes --file conda_requirements.txt
  # Install pip packages
  - pip install -r requirements.txt

# Specify the Sphinx build configuration
sphinx:
  configuration: docs/source/conf.py
