
version: 1.0
build:
  os: ubuntu-22.04
  # Set up Conda
  packages:
    - name: conda
      version: latest
    - name: python
      version: "3.8"
  # Install Conda packages
  install:
    - conda config --add channels conda-forge
    - conda config --add channels schrodinger
    - conda install --yes --file conda_requirements.txt
  # Install pip packages
  - pip install -r requirements.txt

# Specify the Sphinx build configuration
sphinx:
  configuration: docs/source/conf.py
  builder: html

formats:
  - pdf
