
version: 1.0
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt
    - conda: docs/conda_requirements.txt
      #  - conda-forge
      #  - schrodinger
      #  - pymol-bundle

# Specify the Sphinx build configuration
sphinx:
  configuration: docs/source/conf.py
  builder: html

formats:
  - pdf
