
version: 1.0
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  
# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  python:
    version: 3.7
  requirements_file: docs/requirements.txt

# Build documentation for all tags, branches, and pull requests
# This allows for links to work on each version of the documentation
# at https://mdanalysis.readthedocs.io/
build:
  image: latest

# Use the latest version of Sphinx
python:
  version: latest
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
