build:
  os: ubuntu-20.04
  tools:
    # python: "miniconda3-4.7"
    python: "mambaforge-4.10"

# Optionally set the version of Python and requirements required to build your docs
python: 3.8
  install:
    - method: pip
      path: package

conda:
  environment: maintainer/conda/environment.yml
