version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

conda:
  environment: docs/environment.yml

python:
  install:
    - requirements: docs/requirements.txt

